# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.13.1-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.13.1-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yrc/Projects/teaplus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yrc/Projects/teaplus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.13.1-Linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.13.1-Linux-x86_64/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yrc/Projects/teaplus/CMakeFiles /home/yrc/Projects/teaplus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yrc/Projects/teaplus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hk

# Build rule for target.
hk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hk
.PHONY : hk

# fast build rule for target.
hk/fast:
	$(MAKE) -f CMakeFiles/hk.dir/build.make CMakeFiles/hk.dir/build
.PHONY : hk/fast

#=============================================================================
# Target rules for targets named graph

# Build rule for target.
graph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph
.PHONY : graph

# fast build rule for target.
graph/fast:
	$(MAKE) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/build
.PHONY : graph/fast

#=============================================================================
# Target rules for targets named cluster

# Build rule for target.
cluster: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cluster
.PHONY : cluster

# fast build rule for target.
cluster/fast:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/build
.PHONY : cluster/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/build
.PHONY : utils/fast

src/algo.o: src/algo.cc.o

.PHONY : src/algo.o

# target to build an object file
src/algo.cc.o:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/src/algo.cc.o
.PHONY : src/algo.cc.o

src/algo.i: src/algo.cc.i

.PHONY : src/algo.i

# target to preprocess a source file
src/algo.cc.i:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/src/algo.cc.i
.PHONY : src/algo.cc.i

src/algo.s: src/algo.cc.s

.PHONY : src/algo.s

# target to generate assembly for a file
src/algo.cc.s:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/src/algo.cc.s
.PHONY : src/algo.cc.s

src/cluster.o: src/cluster.cc.o

.PHONY : src/cluster.o

# target to build an object file
src/cluster.cc.o:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/src/cluster.cc.o
.PHONY : src/cluster.cc.o

src/cluster.i: src/cluster.cc.i

.PHONY : src/cluster.i

# target to preprocess a source file
src/cluster.cc.i:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/src/cluster.cc.i
.PHONY : src/cluster.cc.i

src/cluster.s: src/cluster.cc.s

.PHONY : src/cluster.s

# target to generate assembly for a file
src/cluster.cc.s:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/src/cluster.cc.s
.PHONY : src/cluster.cc.s

src/graph.o: src/graph.cc.o

.PHONY : src/graph.o

# target to build an object file
src/graph.cc.o:
	$(MAKE) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/src/graph.cc.o
.PHONY : src/graph.cc.o

src/graph.i: src/graph.cc.i

.PHONY : src/graph.i

# target to preprocess a source file
src/graph.cc.i:
	$(MAKE) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/src/graph.cc.i
.PHONY : src/graph.cc.i

src/graph.s: src/graph.cc.s

.PHONY : src/graph.s

# target to generate assembly for a file
src/graph.cc.s:
	$(MAKE) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/src/graph.cc.s
.PHONY : src/graph.cc.s

src/hk.o: src/hk.cc.o

.PHONY : src/hk.o

# target to build an object file
src/hk.cc.o:
	$(MAKE) -f CMakeFiles/hk.dir/build.make CMakeFiles/hk.dir/src/hk.cc.o
.PHONY : src/hk.cc.o

src/hk.i: src/hk.cc.i

.PHONY : src/hk.i

# target to preprocess a source file
src/hk.cc.i:
	$(MAKE) -f CMakeFiles/hk.dir/build.make CMakeFiles/hk.dir/src/hk.cc.i
.PHONY : src/hk.cc.i

src/hk.s: src/hk.cc.s

.PHONY : src/hk.s

# target to generate assembly for a file
src/hk.cc.s:
	$(MAKE) -f CMakeFiles/hk.dir/build.make CMakeFiles/hk.dir/src/hk.cc.s
.PHONY : src/hk.cc.s

src/mtwist.o: src/mtwist.c.o

.PHONY : src/mtwist.o

# target to build an object file
src/mtwist.c.o:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/src/mtwist.c.o
.PHONY : src/mtwist.c.o

src/mtwist.i: src/mtwist.c.i

.PHONY : src/mtwist.i

# target to preprocess a source file
src/mtwist.c.i:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/src/mtwist.c.i
.PHONY : src/mtwist.c.i

src/mtwist.s: src/mtwist.c.s

.PHONY : src/mtwist.s

# target to generate assembly for a file
src/mtwist.c.s:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/src/mtwist.c.s
.PHONY : src/mtwist.c.s

src/sampler.o: src/sampler.cc.o

.PHONY : src/sampler.o

# target to build an object file
src/sampler.cc.o:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/src/sampler.cc.o
.PHONY : src/sampler.cc.o

src/sampler.i: src/sampler.cc.i

.PHONY : src/sampler.i

# target to preprocess a source file
src/sampler.cc.i:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/src/sampler.cc.i
.PHONY : src/sampler.cc.i

src/sampler.s: src/sampler.cc.s

.PHONY : src/sampler.s

# target to generate assembly for a file
src/sampler.cc.s:
	$(MAKE) -f CMakeFiles/cluster.dir/build.make CMakeFiles/cluster.dir/src/sampler.cc.s
.PHONY : src/sampler.cc.s

src/utils.o: src/utils.cc.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cc.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils.cc.o
.PHONY : src/utils.cc.o

src/utils.i: src/utils.cc.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cc.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils.cc.i
.PHONY : src/utils.cc.i

src/utils.s: src/utils.cc.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cc.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils.cc.s
.PHONY : src/utils.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... hk"
	@echo "... rebuild_cache"
	@echo "... graph"
	@echo "... cluster"
	@echo "... utils"
	@echo "... src/algo.o"
	@echo "... src/algo.i"
	@echo "... src/algo.s"
	@echo "... src/cluster.o"
	@echo "... src/cluster.i"
	@echo "... src/cluster.s"
	@echo "... src/graph.o"
	@echo "... src/graph.i"
	@echo "... src/graph.s"
	@echo "... src/hk.o"
	@echo "... src/hk.i"
	@echo "... src/hk.s"
	@echo "... src/mtwist.o"
	@echo "... src/mtwist.i"
	@echo "... src/mtwist.s"
	@echo "... src/sampler.o"
	@echo "... src/sampler.i"
	@echo "... src/sampler.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

